# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+c6a9668
loader_version=0.16.10

# Mod Properties
mod_version=1.0.0
maven_group=com.periut
archives_base_name=starac

# Dependencies
stapi_version=2.0.0-alpha.5.4

# Extra Dependencies
modmenu_version=1.8.5-beta.11

lwjgl_version = 3.4.0