# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=b1.7.3
	feather_build = 1
	loader_version=0.16.10

# Mod Properties
	mod_version=1.2.0
	maven_group=com.periut
	archives_base_name=starac

client_raven_build = 2
server_raven_build = 2
client_sparrow_build = 2
server_sparrow_build = 2
client_nests_build = 7
server_nests_build = 4

lwjgl_version = 3.4.0

# Will probably need to be updated!!
stationapi_version=2.0.0-alpha.5.4